version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "phpunit"
      - dependency-name: "express"
        versions: ["10.x"]
